# Generated by Django 3.0.8 on 2020-08-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='coursemodel',
            name='text',
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='duration_seconds',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='last_mod_date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
