# Generated by Django 3.0.8 on 2020-08-11 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_auto_20200811_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursemodel',
            old_name='created_date',
            new_name='creation_date',
        ),
    ]
