# Generated by Django 3.0.9 on 2020-08-31 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0003_auto_20200811_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('roles', models.ManyToManyField(to='course_app.RoleModel')),
            ],
        ),
        migrations.CreateModel(
            name='CourseTopicModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.TextField()),
                ('synonyms', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_app.CourseTopicModel')),
            ],
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='course_topics',
            field=models.ManyToManyField(to='course_app.CourseTopicModel'),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='expert_skills',
            field=models.ManyToManyField(blank=True, related_name='expert_skills', to='course_app.SkillModel'),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='intermediate_skills',
            field=models.ManyToManyField(blank=True, related_name='intermediate_skills', to='course_app.SkillModel'),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='novice_skills',
            field=models.ManyToManyField(blank=True, related_name='novice_skills', to='course_app.SkillModel'),
        ),
    ]
